# Generated by Django 4.2.3 on 2023-10-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_items_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount',
            field=models.IntegerField(default=5),
        ),
    ]
